module.exports={
    //属性，对webpack进行配置
    configureWebpack:{
        //创建一个模块
        module:{
            //指定规则
            rules:[
                {test:/\.ico$/,use:'file-loader'}
            ]
        }
    }
}
